on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * *'

name: Update bot API

jobs:
  scrap-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: 8.5
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate new API data
        run: composer run generate

      - name: Check if updated
        id: check_api
        run: |
          if git diff --quiet --exit-code; then
            echo "api_changed=false" >> $GITHUB_OUTPUT
          else
            echo "api_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Code Style
        if: steps.check_api.outputs.api_changed == 'true'
        run: |
          vendor/bin/pint
          vendor/bin/rector

      - name: Create Pull Request
        if: steps.check_api.outputs.api_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "[auto] update telegram bot API"
          branch: auto/api-update
          title: "[AUTO] Update Telegram Bot API"
          body: "This pull request was automatically generated by the GitHub Actions workflow."